on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install apko
        run: |
          curl -sSLO "https://github.com/chainguard-dev/apko/releases/download/v0.13.2/apko_0.13.2_linux_amd64.tar.gz"
          echo 95e3f21e01538de4438d67d3c3c841bdcc24fa2eb7b4b1c95265c6d7bfd4dc9d apko_0.13.2_linux_amd64.tar.gz | sha256sum -c -
          tar --strip-components=1 -xf apko_0.13.2_linux_amd64.tar.gz apko_0.13.2_linux_amd64/apko
          mv apko /usr/local/bin/
          rm apko_0.13.2_linux_amd64.tar.gz

      - name: Login to GitHub Container Registry
        run: |
          apko login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Build iperf3
        run: |
          apko publish images/iperf3.yaml ghcr.io/takonomura/iperf3:latest

      - name: Build ip
        run: |
          apko publish images/ip.yaml ghcr.io/takonomura/ip:latest

      - name: Build bird
        run: |
          apko publish images/bird.yaml ghcr.io/takonomura/bird:latest
