on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install apko
        run: |
          curl -sSLO "https://github.com/chainguard-dev/apko/releases/download/v0.19.8/apko_0.19.8_linux_amd64.tar.gz"
          echo 9244f1a3d153bbe7fb102ac956793edb3e05825d157d1e4c5eb5b2eba06ccaea apko_0.19.8_linux_amd64.tar.gz | sha256sum -c -
          tar --strip-components=1 -xf apko_0.19.8_linux_amd64.tar.gz apko_0.19.8_linux_amd64/apko
          mv apko /usr/local/bin/
          rm apko_0.19.8_linux_amd64.tar.gz

      - name: Login to GitHub Container Registry
        run: |
          apko login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Build iperf3
        run: |
          apko publish images/iperf3.yaml ghcr.io/takonomura/iperf3:latest

      - name: Build ip
        run: |
          apko publish images/ip.yaml ghcr.io/takonomura/ip:latest

      - name: Build bird
        run: |
          apko publish images/bird.yaml ghcr.io/takonomura/bird:latest
